### ISSUE TITLE
class 'OC_User_Backend' not found in Nextcloud 13

### ISSUE THREAD

**Issue by bangarangadang** [paroga/user_discourse#1]
when you trying to activate the app on nextcloud 13 following error appears:

`PHP Fatal error:  Class 'OC_User_Backend' not found in /var/www/html/apps/user_discourse/user_discourse.php on line 2`

for nextcloud 13 the class should ne renamed to `\OC\User\Backend`.

**Comment by paroga** [comment]
d2b67ccb6b4c27de6fe79d63e1cbf28a8a2f10bc should be compatible with nextcloud 13.
